[2024-02-27T05:42:00.718+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_trade_data.write_to_motherduck_from_data_frame scheduled__2024-02-26T21:01:00+00:00 [queued]>
[2024-02-27T05:42:00.818+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_trade_data.write_to_motherduck_from_data_frame scheduled__2024-02-26T21:01:00+00:00 [queued]>
[2024-02-27T05:42:00.819+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-27T05:42:00.934+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): write_to_motherduck_from_data_frame> on 2024-02-26 21:01:00+00:00
[2024-02-27T05:42:00.953+0000] {standard_task_runner.py:60} INFO - Started process 16505 to run task
[2024-02-27T05:42:00.969+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'exchange_trade_data', 'write_to_motherduck_from_data_frame', 'scheduled__2024-02-26T21:01:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/exchange.py', '--cfg-path', '/tmp/tmpwg03s8rk']
[2024-02-27T05:42:00.983+0000] {standard_task_runner.py:88} INFO - Job 69: Subtask write_to_motherduck_from_data_frame
[2024-02-27T05:42:01.127+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-27T05:42:01.448+0000] {task_command.py:423} INFO - Running <TaskInstance: exchange_trade_data.write_to_motherduck_from_data_frame scheduled__2024-02-26T21:01:00+00:00 [running]> on host e16193345271
[2024-02-27T05:42:05.278+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_trade_data' AIRFLOW_CTX_TASK_ID='write_to_motherduck_from_data_frame' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T21:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-26T21:01:00+00:00'
[2024-02-27T05:42:21.704+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/exchange.py", line 83, in write_to_motherduck_from_data_frame
    curr.execute(
duckdb.duckdb.TransactionException: TransactionContext Error: Conflict on update!
[2024-02-27T05:42:21.741+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=exchange_trade_data, task_id=write_to_motherduck_from_data_frame, execution_date=20240226T210100, start_date=20240227T054200, end_date=20240227T054221
[2024-02-27T05:42:21.900+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 69 for task write_to_motherduck_from_data_frame (TransactionContext Error: Conflict on update!; 16505)
[2024-02-27T05:42:22.079+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-27T05:42:23.028+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
