[2024-02-25T11:07:51.509+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_trade_data.get_exchange_data scheduled__2024-02-25T08:02:00+00:00 [queued]>
[2024-02-25T11:07:51.640+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_trade_data.get_exchange_data scheduled__2024-02-25T08:02:00+00:00 [queued]>
[2024-02-25T11:07:51.655+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-25T11:07:52.729+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): get_exchange_data> on 2024-02-25 08:02:00+00:00
[2024-02-25T11:07:52.759+0000] {standard_task_runner.py:60} INFO - Started process 2064 to run task
[2024-02-25T11:07:52.817+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'exchange_trade_data', 'get_exchange_data', 'scheduled__2024-02-25T08:02:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/exchange.py', '--cfg-path', '/tmp/tmpijmhjvu2']
[2024-02-25T11:07:52.847+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask get_exchange_data
[2024-02-25T11:07:53.251+0000] {task_command.py:423} INFO - Running <TaskInstance: exchange_trade_data.get_exchange_data scheduled__2024-02-25T08:02:00+00:00 [running]> on host f5283f9a0a92
[2024-02-25T11:07:53.685+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_trade_data' AIRFLOW_CTX_TASK_ID='get_exchange_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-25T08:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-25T08:02:00+00:00'
[2024-02-25T17:12:48.692+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-25T17:12:50.665+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=exchange_trade_data, task_id=get_exchange_data, execution_date=20240225T080200, start_date=20240225T110751, end_date=20240225T171250
[2024-02-25T17:12:51.037+0000] {local_task_job_runner.py:211} ERROR - Heartbeat time limit exceeded!
[2024-02-25T17:12:53.577+0000] {process_utils.py:131} INFO - Sending 15 to group 2064. PIDs of all processes in the group: [2064]
[2024-02-25T17:12:53.578+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 2064
[2024-02-25T17:12:53.702+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2064, status='terminated', exitcode=0, started='11:07:51') (2064) terminated with exit code 0
