[2024-02-24T19:22:10.428+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:10.429+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/coincap_dag.py for tasks to queue
[2024-02-24T19:22:10.433+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:10.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:10.450+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:10.446+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/coincap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/coincap_dag.py", line 17, in <module>
    @dag(
NameError: name 'dag' is not defined
[2024-02-24T19:22:10.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:10.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/coincap_dag.py took 0.111 seconds
[2024-02-24T19:22:26.597+0000] {processor.py:161} INFO - Started process (PID=128) to work on /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:26.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/coincap_dag.py for tasks to queue
[2024-02-24T19:22:26.600+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:26.599+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:26.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:26.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/coincap_dag.py took 0.039 seconds
[2024-02-24T19:22:28.673+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:28.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/coincap_dag.py for tasks to queue
[2024-02-24T19:22:28.676+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:28.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:28.682+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:28.680+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/coincap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/coincap_dag.py", line 14, in <module>
    @dag(
NameError: name 'dag' is not defined
[2024-02-24T19:22:28.683+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:28.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/coincap_dag.py took 0.054 seconds
[2024-02-24T19:22:32.722+0000] {processor.py:161} INFO - Started process (PID=130) to work on /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:32.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/coincap_dag.py for tasks to queue
[2024-02-24T19:22:32.726+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:32.725+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:32.731+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:32.730+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/coincap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/coincap_dag.py", line 12, in <module>
    z
NameError: name 'z' is not defined
[2024-02-24T19:22:32.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:32.769+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/coincap_dag.py took 0.053 seconds
[2024-02-24T19:22:34.852+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:34.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/coincap_dag.py for tasks to queue
[2024-02-24T19:22:34.857+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:34.856+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:34.871+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:34.869+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/coincap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/coincap_dag.py", line 12, in <module>
    @dag(
NameError: name 'dag' is not defined
[2024-02-24T19:22:34.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:34.909+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/coincap_dag.py took 0.071 seconds
[2024-02-24T19:22:37.130+0000] {processor.py:161} INFO - Started process (PID=132) to work on /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:37.132+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/coincap_dag.py for tasks to queue
[2024-02-24T19:22:37.135+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:37.134+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:37.144+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:37.141+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/coincap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/coincap_dag.py", line 5, in <module>
    import duckdb as db
ModuleNotFoundError: No module named 'duckdb'
[2024-02-24T19:22:37.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:37.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/coincap_dag.py took 0.084 seconds
[2024-02-24T19:22:53.319+0000] {processor.py:161} INFO - Started process (PID=139) to work on /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:53.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/coincap_dag.py for tasks to queue
[2024-02-24T19:22:53.329+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:53.328+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:53.346+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:53.344+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/coincap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/coincap_dag.py", line 5, in <module>
    import duckdb as db
ModuleNotFoundError: No module named 'duckdb'
[2024-02-24T19:22:53.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:53.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/coincap_dag.py took 0.123 seconds
[2024-02-24T19:22:58.396+0000] {processor.py:161} INFO - Started process (PID=140) to work on /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:58.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/coincap_dag.py for tasks to queue
[2024-02-24T19:22:58.400+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:58.400+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:58.408+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:22:58.407+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/coincap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/coincap_dag.py", line 5, in <module>
    import duckdb as db
ModuleNotFoundError: No module named 'duckdb'
[2024-02-24T19:22:58.408+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:22:58.484+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/coincap_dag.py took 0.092 seconds
[2024-02-24T19:23:01.552+0000] {processor.py:161} INFO - Started process (PID=141) to work on /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:23:01.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/coincap_dag.py for tasks to queue
[2024-02-24T19:23:01.559+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:23:01.559+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:23:01.571+0000] {logging_mixin.py:188} INFO - [2024-02-24T19:23:01.569+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/coincap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/coincap_dag.py", line 5, in <module>
    import duckdb as db
ModuleNotFoundError: No module named 'duckdb'
[2024-02-24T19:23:01.572+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/coincap_dag.py
[2024-02-24T19:23:01.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/coincap_dag.py took 0.090 seconds
