[2024-02-26T08:02:02.157+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_trade_data.connect_to_md scheduled__2024-02-26T07:02:00+00:00 [queued]>
[2024-02-26T08:02:02.171+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_trade_data.connect_to_md scheduled__2024-02-26T07:02:00+00:00 [queued]>
[2024-02-26T08:02:02.172+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T08:02:02.377+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): connect_to_md> on 2024-02-26 07:02:00+00:00
[2024-02-26T08:02:02.386+0000] {standard_task_runner.py:60} INFO - Started process 4223 to run task
[2024-02-26T08:02:02.393+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'exchange_trade_data', 'connect_to_md', 'scheduled__2024-02-26T07:02:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/exchange.py', '--cfg-path', '/tmp/tmpg1dbd6c6']
[2024-02-26T08:02:02.395+0000] {standard_task_runner.py:88} INFO - Job 62: Subtask connect_to_md
[2024-02-26T08:02:02.461+0000] {task_command.py:423} INFO - Running <TaskInstance: exchange_trade_data.connect_to_md scheduled__2024-02-26T07:02:00+00:00 [running]> on host f5283f9a0a92
[2024-02-26T08:02:02.618+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_trade_data' AIRFLOW_CTX_TASK_ID='connect_to_md' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T07:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-26T07:02:00+00:00'
[2024-02-26T08:02:05.083+0000] {logging_mixin.py:188} INFO - Failed to connect to the database: Invalid Input Error: Initialization function "motherduck_init" from file "/home/***/.duckdb/extensions/v0.9.2/linux_amd64_gcc4/motherduck.duckdb_extension" threw an exception: "Invalid Input Error: Initialization function "motherduck_init" from file "/home/***/.duckdb/extensions/v0.9.2/linux_amd64_gcc4/motherduck.v1.15.17.duckdb_extension" threw an exception: "IO Error: RPC 'GET_WELCOME_PACK' failed: Jwt is not in the form of Header.Payload.Signature with two dots and 3 sections (UNAUTHENTICATED, request id: '818de46f-6fe2-4dd5-97ee-b9bd167b571e')""
[2024-02-26T08:02:05.084+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-26T08:02:05.099+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=exchange_trade_data, task_id=connect_to_md, execution_date=20240226T070200, start_date=20240226T080202, end_date=20240226T080205
[2024-02-26T08:02:05.135+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-26T08:02:05.170+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-26T08:13:06.050+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_trade_data.connect_to_md scheduled__2024-02-26T07:02:00+00:00 [queued]>
[2024-02-26T08:13:06.078+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_trade_data.connect_to_md scheduled__2024-02-26T07:02:00+00:00 [queued]>
[2024-02-26T08:13:06.079+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T08:13:06.324+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): connect_to_md> on 2024-02-26 07:02:00+00:00
[2024-02-26T08:13:06.332+0000] {standard_task_runner.py:60} INFO - Started process 5459 to run task
[2024-02-26T08:13:06.339+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'exchange_trade_data', 'connect_to_md', 'scheduled__2024-02-26T07:02:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/exchange.py', '--cfg-path', '/tmp/tmplcnl0dql']
[2024-02-26T08:13:06.341+0000] {standard_task_runner.py:88} INFO - Job 73: Subtask connect_to_md
[2024-02-26T08:13:06.428+0000] {task_command.py:423} INFO - Running <TaskInstance: exchange_trade_data.connect_to_md scheduled__2024-02-26T07:02:00+00:00 [running]> on host f5283f9a0a92
[2024-02-26T08:13:06.624+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_trade_data' AIRFLOW_CTX_TASK_ID='connect_to_md' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T07:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-26T07:02:00+00:00'
[2024-02-26T08:13:09.655+0000] {logging_mixin.py:188} INFO - Failed to connect to the database: Invalid Input Error: Initialization function "motherduck_init" from file "/home/***/.duckdb/extensions/v0.9.2/linux_amd64_gcc4/motherduck.duckdb_extension" threw an exception: "Invalid Input Error: Initialization function "motherduck_init" from file "/home/***/.duckdb/extensions/v0.9.2/linux_amd64_gcc4/motherduck.v1.15.17.duckdb_extension" threw an exception: "IO Error: RPC 'GET_WELCOME_PACK' failed: Jwt is not in the form of Header.Payload.Signature with two dots and 3 sections (UNAUTHENTICATED, request id: '818de479-93da-455f-adf5-e7deda8f6c11')""
[2024-02-26T08:13:09.656+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-26T08:13:09.677+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=exchange_trade_data, task_id=connect_to_md, execution_date=20240226T070200, start_date=20240226T081306, end_date=20240226T081309
[2024-02-26T08:13:09.760+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-26T08:13:09.815+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
